window.showboxes = [
  [ // Lampe 1: Big Player LLMs Logos (Glow & Gradients)
    "<div style='display:flex; flex-direction:column; align-items:center; gap:20px;'><span style='color:#fff; text-shadow:0 0 20px rgba(0, 150, 255, 0.8); font-size:1.2em;'>BIG PLAYER LLMS</span><div style='display:grid; grid-template-columns: repeat(2, 1fr); gap:20px; width:100%; max-width:600px; margin-top:20px;'><div style='background:rgba(255,255,255,0.03); border:1px solid rgba(16,163,127,0.3); border-radius:12px; padding:20px; text-align:center; box-shadow:0 0 15px rgba(16,163,127,0.1);'><span style='color:#10a37f; font-size:1.5rem; font-weight:900; filter:drop-shadow(0 0 8px #10a37f);'>OpenAI</span><p style='font-size:0.4em; color:#aaa; margin-top:5px;'>GPT-4o & o1 reasoning</p></div><div style='background:rgba(255,255,255,0.03); border:1px solid rgba(212,163,115,0.3); border-radius:12px; padding:20px; text-align:center; box-shadow:0 0 15px rgba(212,163,115,0.1);'><span style='color:#d4a373; font-size:1.5rem; font-weight:900; filter:drop-shadow(0 0 8px #d4a373);'>Anthropic</span><p style='font-size:0.4em; color:#aaa; margin-top:5px;'>Claude 3.5 Sonnet</p></div><div style='background:rgba(255,255,255,0.03); border:1px solid rgba(77,144,254,0.3); border-radius:12px; padding:20px; text-align:center; box-shadow:0 0 15px rgba(77,144,254,0.1);'><span style='color:#4d90fe; font-size:1.5rem; font-weight:900; filter:drop-shadow(0 0 8px #4d90fe);'>DeepSeek</span><p style='font-size:0.4em; color:#aaa; margin-top:5px;'>V3 & R1 Open Source</p></div><div style='background:rgba(255,255,255,0.03); border:1px solid rgba(66,133,244,0.3); border-radius:12px; padding:20px; text-align:center; box-shadow:0 0 15px rgba(66,133,244,0.1);'><span style='color:#4285f4; font-size:1.5rem; font-weight:900; filter:drop-shadow(0 0 8px #4285f4);'>Gemini</span><p style='font-size:0.4em; color:#aaa; margin-top:5px;'>Google Advanced AI</p></div></div></div>",
    "<div style='display:flex; flex-direction:column; align-items:center; justify-content:center; height:100%;'><div style='background:rgba(16,163,127,0.1); border:2px solid #10a37f; border-radius:50%; width:100px; height:100px; display:flex; align-items:center; justify-content:center; box-shadow:0 0 30px rgba(16,163,127,0.4); margin-bottom:20px;'><span style='color:#10a37f; font-size:3rem;'>O</span></div><span style='color:#10a37f; text-shadow:0 0 15px rgba(16,163,127,0.6); font-size:1.2em;'>OPENAI GPT-4o</span><span style='font-size:0.4em; color:#aaa; max-width:500px; margin-top:15px; font-weight:400;'>Der globale Standard für logische Argumentation und schnelle, präzise Antworten. Voll integriert in Gnom-Hub.</span></div>",
    "<div style='display:flex; flex-direction:column; align-items:center; justify-content:center; height:100%;'><div style='background:rgba(212,163,115,0.1); border:2px solid #d4a373; border-radius:50%; width:100px; height:100px; display:flex; align-items:center; justify-content:center; box-shadow:0 0 30px rgba(212,163,115,0.4); margin-bottom:20px;'><span style='color:#d4a373; font-size:3rem;'>A</span></div><span style='color:#d4a373; text-shadow:0 0 15px rgba(212,163,115,0.6); font-size:1.2em;'>CLAUDE 3.5 SONNET</span><span style='font-size:0.4em; color:#aaa; max-width:500px; margin-top:15px; font-weight:400;'>Brillantes Verständnis von Code, Dokumentenstruktur und kreativem Texting. Ideal für das Refactoring.</span></div>"
  ],
  [ // Lampe 2: Command Reference (@ und @@ Beispiele)
    "<div style='display:flex; flex-direction:column; align-items:center; gap:20px;'><span style='color:var(--cyan); text-shadow:0 0 20px rgba(0,255,204,0.6); font-size:1.2em;'>BEFEHLE VERSTEHEN</span><div style='display:grid; grid-template-columns: 1fr 1fr; gap:20px; width:100%; max-width:650px; margin-top:10px; text-align:left;'><div style='background:rgba(255,255,255,0.02); border:1px solid rgba(0,255,255,0.15); border-radius:10px; padding:15px;'><span style='color:var(--cyan); font-size:0.7em; font-weight:bold;'>🎯 @ [Agent] (Targeting)</span><p style='font-size:0.35em; color:#bbb; margin-top:5px; line-height:1.4;'>Spricht einen spezifischen Agenten an oder startet Schwarm-Prozesse.</p><code style='display:block; background:#000; padding:6px; font-size:0.32em; border-radius:4px; margin-top:8px; color:#fff;'>@coderag optimiere code.py</code></div><div style='background:rgba(255,255,255,0.02); border:1px solid rgba(255,100,255,0.15); border-radius:10px; padding:15px;'><span style='color:#ff00ff; font-size:0.7em; font-weight:bold;'>⚙️ @@ [Command] (System)</span><p style='font-size:0.35em; color:#bbb; margin-top:5px; line-height:1.4;'>Steuert Gnom-Hub Kernfunktionen, Git, LLM-Provider oder Rollbacks.</p><code style='display:block; background:#000; padding:6px; font-size:0.32em; border-radius:4px; margin-top:8px; color:#fff;'>@@status</code></div></div></div>",
    "<div style='display:flex; flex-direction:column; align-items:left; text-align:left; max-width:600px; margin:0 auto; gap:10px;'><span style='color:var(--cyan); font-size:0.9em; font-weight:bold; border-bottom:1px solid rgba(255,255,255,0.1); padding-bottom:5px; margin-bottom:10px;'>AGENTEN ANSPRECHEN (@)</span><div style='font-size:0.42em; line-height:1.5; color:#bbb; display:flex; flex-direction:column; gap:8px;'><div><strong style='color:#fff;'>@bs</strong>: Startet ein Brainstorming im Agenten-Schwarm für komplexe Problemstellungen.</div><div><strong style='color:#fff;'>@research [task]</strong>: Delegiert eine autonome Web- und Datei-Recherche.</div><div><strong style='color:#fff;'>@job [agent] [task]</strong>: Weist einem Agenten im Hintergrund eine dedizierte Aufgabe zu.</div></div></div>",
    "<div style='display:flex; flex-direction:column; align-items:left; text-align:left; max-width:600px; margin:0 auto; gap:10px;'><span style='color:#ff00ff; font-size:0.9em; font-weight:bold; border-bottom:1px solid rgba(255,255,255,0.1); padding-bottom:5px; margin-bottom:10px;'>SYSTEM-BEFEHLE (@@)</span><div style='font-size:0.42em; line-height:1.5; color:#bbb; display:flex; flex-direction:column; gap:8px;'><div><strong style='color:#fff;'>@@provider [name]</strong>: Wechselt live das genutzte LLM (z.B. <code style='color:var(--cyan);'>@@provider ollama llama3</code>).</div><div><strong style='color:#fff;'>@@git [args]</strong>: Führt Git-Kommandos direkt im Repository aus (z.B. <code style='color:var(--cyan);'>@@git status</code>).</div><div><strong style='color:#fff;'>@@rollback</strong>: Setzt den Code auf einen früheren Swarm Checkpoint zurück.</div></div></div>"
  ],
  [ // Lampe 3: Mouseover Direct Hilfe
    "<div style='display:flex; flex-direction:column; align-items:center; gap:10px; width:100%; height:100%; justify-content:center;'><span style='color:#ffcc00; text-shadow:0 0 20px rgba(255,204,0,0.6); font-size:1.1em; margin-bottom:5px;'>INTERFACE-KOMPASS</span><p style='font-size:0.35em; color:#aaa; margin-bottom:15px;'>Bewege die Maus über die Bereiche der App-Vorschau für Direkt-Hilfe:</p><div style='position:relative; width:450px; height:220px; background:#0c0f1d; border:2px solid rgba(255,255,255,0.1); border-radius:8px; padding:8px; box-sizing:border-box; display:flex; flex-direction:column; gap:6px; font-size:12px; font-family:sans-serif;'><div style='height:30px; background:#161a30; border-radius:4px; display:flex; justify-content:space-between; align-items:center; padding:0 8px; position:relative; cursor:help;' title='STATUS-BAR & LAMPS: Zeigt Serverstatistiken und steuert die Showboxen.'><span style='font-size:8px; color:var(--cyan);'>GNOM-HUB Mock</span><div style='display:flex; gap:3px;'><div style='width:6px; height:6px; background:#ff3366; border-radius:50%;'></div><div style='width:6px; height:6px; background:#00ffcc; border-radius:50%;'></div><div style='width:6px; height:6px; background:#ffcc00; border-radius:50%;'></div></div></div><div style='display:flex; gap:6px; flex:1;'><div style='width:120px; background:#111428; border-radius:4px; padding:6px; display:flex; flex-direction:column; gap:4px; cursor:help;' title='AGENTEN-LISTE: Zeigt alle installierten Agenten und deren Live-Status (online/busy).'><div style='height:12px; background:rgba(255,255,255,0.05); border-radius:2px;'></div><div style='flex:1; display:flex; flex-direction:column; gap:3px;'><div style='display:flex; align-items:center; gap:4px;'><div style='width:4px; height:4px; background:#0f0; border-radius:50%;'></div><div style='width:50px; height:6px; background:#333; border-radius:1px;'></div></div><div style='display:flex; align-items:center; gap:4px;'><div style='width:4px; height:4px; background:#ffaa00; border-radius:50%;'></div><div style='width:40px; height:6px; background:#333; border-radius:1px;'></div></div></div></div><div style='flex:1; background:#131730; border-radius:4px; padding:8px; display:flex; flex-direction:column; justify-content:space-between; cursor:help;' title='WAR ROOM CHAT: Das Herzstück für Agenten-Diskussionen und deine Steuerung.'><div style='display:flex; flex-direction:column; gap:4px;'><div style='width:80px; height:6px; background:rgba(255,255,255,0.1); border-radius:1px;'></div><div style='width:130px; height:6px; background:rgba(255,255,255,0.05); border-radius:1px;'></div></div><div style='height:20px; background:#1a1f3c; border-radius:3px; display:flex; align-items:center; padding:0 6px;'><span style='font-size:7px; color:#666;'>@bs Schreibe...</span></div></div></div></div></div>"
  ],
  [ // Lampe 4: Vorschau index.html & Built files
    "<div style='display:flex; flex-direction:column; align-items:center; gap:10px; width:100%; height:100%; justify-content:center;'><span style='color:#00ffcc; text-shadow:0 0 20px rgba(0,255,204,0.6); font-size:1.1em;'>CODE-PREVIEW & ARCHITEKTUR</span><p style='font-size:0.35em; color:#aaa; margin-bottom:10px;'>Diese Dateien wurden neu im System implementiert & verfeinert:</p><div style='width:100%; max-width:600px; display:flex; flex-direction:column; gap:6px; text-align:left;'><div style='background:rgba(255,255,255,0.03); border:1px solid rgba(0, 255, 204, 0.2); border-radius:6px; padding:8px 12px; display:flex; justify-content:space-between; align-items:center;'><div><span style='font-size:0.45em; font-family:monospace; color:#fff; font-weight:bold;'>frontend/index.html</span><p style='font-size:0.32em; color:#888; margin-top:2px;'>Zentrale SPA mit Dynamic Model Lists, System-Hardware Status & Showbox Center.</p></div><span style='font-size:0.35em; color:var(--cyan); background:rgba(0,255,204,0.1); padding:2px 6px; border-radius:4px;'>99 KB</span></div><div style='background:rgba(255,255,255,0.03); border:1px solid rgba(0, 255, 204, 0.2); border-radius:6px; padding:8px 12px; display:flex; justify-content:space-between; align-items:center;'><div><span style='font-size:0.45em; font-family:monospace; color:#fff; font-weight:bold;'>src/gnom_hub/routes_showbox.py</span><p style='font-size:0.32em; color:#888; margin-top:2px;'>FastAPI-Router für sichere CRUD-Operationen auf der themes.js-Datei.</p></div><span style='font-size:0.35em; color:var(--cyan); background:rgba(0,255,204,0.1); padding:2px 6px; border-radius:4px;'>21 Zeilen</span></div><div style='background:rgba(255,255,255,0.03); border:1px solid rgba(0, 255, 204, 0.2); border-radius:6px; padding:8px 12px; display:flex; justify-content:space-between; align-items:center;'><div><span style='font-size:0.45em; font-family:monospace; color:#fff; font-weight:bold;'>src/gnom_hub/sandbox_exec.py</span><p style='font-size:0.32em; color:#888; margin-top:2px;'>Sichere Sandbox-Umgebung mittels macOS seatbelt-Profilen.</p></div><span style='font-size:0.35em; color:var(--cyan); background:rgba(0,255,204,0.1); padding:2px 6px; border-radius:4px;'>38 Zeilen</span></div></div></div>"
  ],
  [ // Lampe 5: Use Cases
    "<span style='color:#ff00ff; text-shadow:0 0 20px rgba(255,0,255,0.6);'>USE CASES</span><br><span style='font-size:0.3em;color:#fff;'>Was macht man damit?</span>",
    "DIGITAL<br>SIGNAGE<br><span style='font-size:0.3em;color:#aaa;font-weight:normal;'>Messe-Modus & Präsentationen</span>",
    "BRAINSTORMING<br>ORCHESTRATOR<br><span style='font-size:0.3em;color:#aaa;font-weight:normal;'>KI-Teams lösen komplexe Probleme</span>",
    "RAPID<br>PROTOTYPING<br><span style='font-size:0.3em;color:#aaa;font-weight:normal;'>Idee -> Code -> Showbox Render</span>"
  ],
  [ // Lampe 6: Agenten Registry
    "7 SYSTEM<br>AGENTEN<br><span style='font-size:0.3em;color:var(--primary);'>Die Säulen des Hubs</span>",
    "WATCHDOG<br>SKILLS<br>SOUL<br><span style='font-size:0.3em;color:#aaa;font-weight:normal;'>Autonome Überwachung & Charakter</span>",
    "ZUKUNFT<br><span style='font-size:0.3em;color:#fff;font-weight:normal;'>Unendlich viele Custom-Agenten ladbar</span>"
  ],
  [ // Lampe 7: Call to Action / Ende
    "<span style='color:#fff; text-shadow:0 0 30px #fff;'>READY?</span><br><span style='font-size:0.3em;color:var(--cyan);'>Tippe einfach in den Chat oder aktiviere das Mic.</span>",
    "GNOM-HUB<br>v2.0<br><span style='font-size:0.3em;color:#fff;'>The Future of Agentic Workflow</span>"
  ]
];
